sonar.projectKey=thangtrantoan_react-todo
sonar.organization=thangtrantoan
sonar.host.url=https://sonarcloud.io
sonar.login=1078b3711114c79ada37416578eae7e18ef9dee8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.*,(**/*.spec.*)
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.*,**/*.spec.*

sonar.javascript.lcov.reportPaths=coverage/lcov.info